### ISSUE TITLE
Architect configs

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#17]
<placeholder>

**Comment by pgebheim** [comment]
see https://github.com/AugurProject/turbo/issues/13 as well

**Comment by robert-e-davidson3** [comment]
This ticket is for figuring out how to properly handle various environments AND work well with clients. I don't believe we will be certain of our configuration architecture until we integrate a UI. The config as-is works well for deployment so it's just the frontend that is unknown.

The only concrete work right now is adding addresses to the hardhat config. The tricky part is _automatically_ adding them to the hardhat config after deploy. There's also the question of exactly where addresses should live, since in the past we have wanted several deploys in kovan. Also we want different sets of contracts for different usecases.
