### ISSUE TITLE
Set all dependencies to definite versions

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/turbo#31]
The versioning system npm uses is ambitious with regards to how often breaking changes occur in patches.

This ticket is for reducing that uncertainty by removing the `^` part of dependency versions. There may be other good work to do here too, like trimming down yarn.lock where versions differ only mildly... or doing the simplification then rebuilding yarn.lock.

**Comment by JohnDanz** [comment]
I don't know if we really want to do that for UI stuff. IMO theres no reason to lock our react versions -- we should be updating when they update -- if something is going to break that we use then we should fix it instead of using the old version that may have a bug/vulnerability or reason why that function is now deprecated. might be something to look at case by case when it comes to the visual elements at least.
