### ISSUE TITLE
Use a permit messages for ERC20 approvals

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#33]
This task will reduce number of transactions users need to submit to one by "pre approving" another contract with an erc20 via a signed message.

See: https://soliditydeveloper.com/erc20-permit
Spec: https://eips.ethereum.org/EIPS/eip-2612

**Comment by namankumar** [comment]
@pgebheim review please. Based on previous discussion, permit messages do NOT reduce number of approvals. Right? If yes, then this doesn't need to be high priority. 

cc: @Chwy5

**Comment by namankumar** [comment]
Need a better effort estimate to determine priority.

**Comment by robert-e-davidson3** [comment]
> @pgebheim review please. Based on previous discussion, permit messages do NOT reduce number of approvals. Right? If yes, then this doesn't need to be high priority.
> 
> cc: @Chwy5

The UX with and without permit messages is very similar on Polygon. In both cases, the user will be presented with two popups requiring their private key. With permit, one of those popups does NOT require a transaction to be committed to the blockchain.

The difference is meaningful on ethereum because it's slower and more expensive. I don't think we gain much from this on Polygon.

In terms of effort, the contract change is just to use OpenZepplin's [draft ERC20Permit extension](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/aefcb3e8aa4ee8da8e2b7022ffe4dcb57fbb0fdf/contracts/token/ERC20/extensions/draft-ERC20Permit.sol). I'm not sure how worried we need to be about it being a draft. Tests will also need to be added so the total effort is 1-3 days.

UI effort is likely to be a much bigger deal but I can only speculate.

**Comment by Chwy5** [comment]
Agree, sounds like little benefit to do on polygon....closing
