### ISSUE TITLE
add pool totalSupply to add and remove liquidity logs

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#477]
Add to remove and add liquidity logs the balancer pools total supply. The call is `pool.totalSupply()`

**Comment by JohnDanz** [comment]
to expand on this. Let's take these 4 actions here:

```
ADD + 100 shares, + $500, Total Complete Set Supply: 100, expected % of pool: 100%
ADD + ~28.51 shares, + $200, Total Complete Set Supply: ~128.51, expected % of pool: 22.22%
ADD + ~214.29 shares, + $1,500, Total Complete Set Supply: ~342.80, expected % of pool: 62.5%
REMOVE - ~214.29 shares, - $1,500, Total Complete Set Supply: ~128.51,  expected % of pool: 62.5%
```
The problem here is the UI then takes the current total supply at time of viewing the page of 128.5 and say the 214.29 share figure in the final two transactions and tells the user that they added or withdrew `166%` of the pool, when in reality if we were comparing against the current total supplies at the time it would be `62.5%` of the pool. It also incorrectly tells the first transaction that they have only added 77.8% of the pool when in reality at the time it was 100% of the pool.

**Comment by robert-e-davidson3** [comment]
Is this still needed?

**Comment by bconfortin** [comment]
@robert-e-davidson3 I believe this is done
