### ISSUE TITLE
Fees charged are not consistent and can potentially be avoided by users

### ISSUE THREAD

**Issue by nuevoalex** [AugurProject/turbo#520]
There are 3 fees specified currently in the `AbstractMarketFactory`:

- Staker
- Settlement
- Protocol

The `staker fee` is the payment to REP holders and is currently _only_ taken on claiming winnings. This fee is currently set to 0, and this issue happens if that fee is increased > 0. For the burning of complete sets it is not charged. This presents a bad incentive to collect losing shares and bypass the REP holder fee. Assuming a staker fee X it would be trivial to just create a "cash out" contract for losers and winners that distributed the would-be fees of REP holders among them with a cut for the contract holder (or not if they just wanted to be malicious).

One approach to prevent the case above would be to prevent the manual calling of burning complete sets by external users after a market has ended. I haven't deeply thought through the non technical aspects of that but it would remove the total bypass of fees scenario.

Additionally when winnings are claimed there is a "settlement" fee charged which goes to the settlement address provided by the market creator, so presumably to the market creator themselves. However this is not charged when burning complete sets. Similar to above you could prevent abuse if it is desired that the market creator only make fees from the final cashing out.

In both of these cases even if a restriction on burning complete sets is added there is still a sort of strange incentive for people to attempt and close out just before market resolution to avoid fees.

Finally there is another fee called a "protocol" fee which I believe is intended to be paid to the market creator as well but it labeled distinctly because the market creator is assumed to be a "protocol". If that is correct it seems like this should potentially just be the "settlement" fee. If it is actually distinct I believe the problems above are more serious since bigger discrepancies in the fees charged based on how shares are cashed out will create confusion as well as ways to cheat the system out of fees.

**Comment by pgebheim** [comment]
Just to clarify, there are currently 4 fees designated in the contracts.

1) Staker Fee - Happens only on claiming. These fees go into a FeePot and REP holders may stake their REP on that fee pot to earn fees This is currently set to 0 and would require a contract upgrade to increase.
2) Protocol Fee - Happens only on burn complete sets. This fee is a future-proofing fee which would allow fees to be sent to a DAO or something else that may make sense in the future. This fee is also currently set to 0.
3) Settlement Fee - Happens only on claiming. This fee goes is gathered to pay oracles to provide data for whatever market types they provide. This is currently set to 0.05%.
4) Trading Fee - This happens during swaps and will got o LPs, this is currently set to 1.5%'

The attack described is less about (1) "Staker Fees" vs (2) "Protocol Fees" because these are both currently set to 0. If those values ever diverged from being equal in the future then yes, the attack above would indeed work.

HOWEVER, the (3) Settlement fee is still only charged on claiming, and so someone could do the attack above to save 0.05% on claiming which would reduce the protocol's ability to pay oracles for their data.

Given that the current settlement fee is set so low (0.05%) there isn't very much profit to be made here, but it is indeed a possibility. I believe the solution of stopping burning complete sets at markets resolution appropriately stops this attack and also makes sense with the rest of the model.

Additionally this points out that the general fee model here should be adjusted so that the `Staker Fee` and `Protocol Fee` should both happen on burn complete sets, this makes the whole model much more sensible.
