### ISSUE TITLE
Markets should be filtered out before market creation if both teams (or Players) are not listed

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/turbo#560]
![image](https://user-images.githubusercontent.com/41301809/118887144-f0a0ba00-b8c7-11eb-9048-b598cedb664e.png)

**Comment by robert-e-davidson3** [comment]
I believe this is because our teams.json file is outdated. We should update it before pushing UI builds.

The TBD text comes from that teams.json file and is associated with nonzero team ids. So these are probably real teams that just weren't known to TheRundown when we originally pulled their team data.

I don't think this is related to the market creation flow because the link node adapter filters out events that don't have both teams specified.

**Comment by robert-e-davidson3** [comment]
I was wrong: this is going to keep happening because the TBD team is used by TheRundown when a game is scheduled but the teams aren't yet known. The fix is to filter out those events in the link node adapter.

I made a PR for them to do that:
https://github.com/smartcontractkit/external-adapters-js/pull/561/files
