### ISSUE TITLE
Use Odds provided by CL to set weights on market pool

### ISSUE THREAD

**Issue by justinbarry** [AugurProject/turbo#691]
we wanna set the weight and initial prices for head to head, from the lines
the spread and overunder can be 50 50

**Comment by robert-e-davidson3** [comment]
@tuvalusoftware Right now the first liquidity provider sets the initial balancer pool weights for markets. We restrict this in the UI but need to do so in the contracts themselves to firmly prevent trolling.

The AMMFactory creates the pools but we want the weights to come from the market factories. Probably something like `getWeights(uint256 _marketId) public override returns (uint256[] _weights)`.

We want spread and over-under markets to be set to 50/50. The head-to-head markets are tricky: we need to derive the odds from the moneyline lines. They give odds but they seem to include the vig but we don't know if 1) it's proportional so you can just remove it from both sides or 2) if disproportional vig makes enough difference in practice to worry about.

One consequence of this change is that head-to-head markets should only be created once we have a line for them. For MLB this can happen very late. We have code for creating head-to-head markets before we have any lines then creating spread and over-under after we have lines. This logic can be simplified since we will never want markets without lines. This also means events without lines can be filtered out in the adapter on creation.

**Comment by robert-e-davidson3** [comment]
In addition to always creating all markets from an event, we should also make it an error to attempt to create markets from a give event twice. This will be the default behavior for MMA/UFC but should apply to MLB, NBA, and future NFL etc market factories.

This doesn't have to happen for this ticket but if it gets punted then a new ticket should be filed for that work.

**Comment by robert-e-davidson3** [comment]
Two PRs:
- https://github.com/AugurProject/external-adapters-js/pull/7
- https://github.com/AugurProject/turbo/pull/984
