### ISSUE TITLE
estimations for UI display

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#93]
need assistance on what calls or methods are needed to estimate:
 - add liquidity
 - remove liquidity
 - buy
 - sell

**Comment by robert-e-davidson3** [comment]
Instead of `contract.addLiquidity` do `contract.callStatic.addLiquidity`, etc. This requires prior approvals but will return several useful values:
addLiquidity -> total lp tokens acquired
removeLiquidity -> total sets sold, which can be converted into total collateral received with numticks
buy -> how many shares you acquired
sell -> total sets you sold, which can be converteed into total collateral received with numticks

If you want gas estimates then use `estimateGas` instead of `callStatic`.

**Comment by justinbarry** [comment]
@bthaile Is this sufficient?

**Comment by bthaile** [comment]
I'll know more when I dig into it. Seems fine for add/remove liq. What about buy/sell?

**Comment by bthaile** [comment]
I need to know what to pass in for _swaps in sell. @justinbarry

**Comment by bthaile** [comment]
I need token balances the user will receive when the user removes liquidity.

**Comment by bthaile** [comment]
close this ticket the estimations are done, there is work left on remove liquidity to return the token balances needed to display in the UI.
